[
	{
		title:'Primeros pasos',
		intro:'a b c d e f g h i j k l m n o p q r s t u v w x y z a a a a a a a a a a a a a a a a a a a a a a',
		url:'data/articulo1.html',
		hasChild:true,
		header:'Semana 1',
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Segundos pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo2.html',
		hasChild:true,
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Primeros pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo1.html',
		hasChild:true,
		header:'Semana 2',
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Primeros pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo1.html',
		hasChild:true,
		header:'Semana 3',
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Segundos pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo2.html',
		hasChild:true,
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Primeros pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo1.html',
		hasChild:true,
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Primeros pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo1.html',
		hasChild:true,
		header:'Semana 4',
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Segundos pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo2.html',
		hasChild:true,
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Primeros pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo1.html',
		hasChild:true,
		header:'Semana 5',
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Primeros pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo1.html',
		hasChild:true,
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Segundos pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo2.html',
		hasChild:true,
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Primeros pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo1.html',
		hasChild:true,
		header:'Semana 6',
		leftImage:'data/images/prueba.png',
	},
	{
		title:'Segundos pasos',
		intro:'Una donna celiaca come deve comportarsi in gravidanza?',
		url:'data/articulo2.html',
		hasChild:true,
		leftImage:'data/images/prueba.png',
	}	
]