var data = [
	{
		title:'Concepimento',
		intro:'La tua gravidanza ha avuto inizio con il concepimento, quando uno spermatozoo è riuscito a fecondare il tuo ovulo.',
		url:'data/a1.html',
		hasChild:true,
		header:'Settimana 1',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Durante la prima settimana di gravidanza non si verificheranno mutamenti evidenti nel tuo fisico. Alcune donne però “percepiscono” di essere incinte poco dopo il concepimento, prima ancora del ritardo mestruale. Sei una di loro?',
		url:'data/a7.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Il sesso del feto',
		intro:'Il sesso del nascituro si determina al momento del concepimento, come tutte le sue caratteristiche fisiche. Gli organi genitali si definiscono durante la 12ª settimana di gravidanza.',
		url:'data/a4.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Sviluppo del feto',
		intro:'La fecondazione è avvenuta e l’uovo fecondato ha preso il nome di zigote.',
		url:'data/a2.html',
		hasChild:true,
		header:'Settimana 2',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Durante la seconda settimana di gravidanza le tue ovaie hanno cominciato a far maturare un ovocita che è stato espulso nella tuba di Falloppio durante l’ovulazione.',
		url:'data/a8.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Tube di Falloppio',
		intro:'Oltre a favorire il passaggio dell’ovulo rilasciato dall’ovaio verso l’utero, le tube di Falloppio svolgono un importante compito durante la fecondazione perché captano l’ovocita e lo spermatozoo affinché avvenga il concepimento.',
		url:'data/a5.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Morula e blastocisti',
		intro:'Lo zigote ha continuato a dividersi fino a trasformarsi in una minuscola pallina solida costituita da 16-32 cellule. Questa pallina, grossa quanto una capocchia di spillo, è denominata morula.',
		url:'data/a3.html',
		hasChild:true,
		header:'Settimana 3',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Se ancora non sai di essere rimasta incinta è probabile che a partire proprio dalla 3ª settimana possa cominciare a sentire i primi sintomi della gravidanza ma non vedrai ancora nessun cambiamento a livello fisico.',
		url:'data/a9.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Embrione e placenta',
		intro:'Il termine embrione è usato per denominare il bambino durante le prime nove settimane di gravidanza. Nel periodo successivo, a partire dalla 10ª settimana, si parla di feto. Sapevi che la sua fonte principale di alimentazione viene dalla placenta?',
		url:'data/a6.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'La 4ª settimana coincide con con l’arrivo della blastocisti nel tuo utero. È il momento dell’impianto. Il tuo bambino ha già due settimane e misura tra 0,36 e 1 mm dalla testa al sacro.',
		url:'data/a10.html',
		hasChild:true,
		header:'Settimana 4',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sai di essere incinta perché il test di gravidanza ti ha dato la conferma. Dentro di te sta succedendo qualcosa di importante. Per i cambiamenti visibili all’esterno dovrai ancora aspettare un po’...',
		url:'data/a11.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Curiosità',
		intro:'Lo sapevi che l’impianto  della blastocisti fallisce spesso perché l’attacco all’endometrio è un’impresa ardua?',
		url:'data/a12.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Le dimensioni del bambino adesso sono quelle di un seme di sesamo. È come un piccolo girino di essere umano che si può vedere solo al microscopio e ha la forma di un manubrio di ginnastica.',
		url:'data/a13.html',
		hasChild:true,
		header:'Settimana 5',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Se il ciclo mestruale è saltato e un secondo test di gravidanza conferma che sei in dolce attesa, prendi appuntamento con il medico.',
		url:'data/a14.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Ginnastica da incinta',
		intro:'Sei da sempre una sportiva e adesso che hai scoperto di essere incinta, non sai se puoi continuare a svolgere attività fisica?',
		url:'data/a15.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Lo sapevi che alla 6ª settimana di gravidanza il tuo bambino è grande come un dado? Ha ancora la coda e assomiglia a un girino, con la schiena e la parte finale ricurve.',
		url:'data/a16.html',
		hasChild:true,
		header:'Settimana 6',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla 6ª settimana di gravidanza: niente ciclo mestruale, test di gravidanza positivo, il tuo seno è gonfio e dolente e ti senti stanchissima. Niente di sorprendente.',
		url:'data/a17.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Ormoni',
		intro:'La gravidanza coincide con un periodo di forte iperattività degli ormoni.',
		url:'data/a18.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Lo sapevi che alla 7ª settimana di gravidanza il viso del tuo bambino ha cominciato ad assumere una fisionomia umana?',
		url:'data/a19.html',
		hasChild:true,
		header:'Settimana 7',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Alla settima settimana di gravidanza puoi avvertire che qualcosa dentro di te sta cambiando.',
		url:'data/a20.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Grandi cambiamenti',
		intro:'Pensare che dal punto di vista fisico la gravidanza significhi soltanto una pancia che cresce è un errore. Il tuo corpo deve attrezzarsi a “far spazio” al nascituro e questo comporterà una serie di cambiamenti.',
		url:'data/a21.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Il tuo bambino già all’ottava settimana ha un abbozzo di lingua e di naso, di cui si può vedere la punta.',
		url:'data/a22.html',
		hasChild:true,
		header:'Settimana 8',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'All’ottava settimana di gravidanza è già tempo d verificare se stai bene, se tutto dentro di te sta procedendo come dovrebbe.',
		url:'data/a23.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Ecografia',
		intro:'All’ottava settimana di gravidanza è già arrivato il momento di fare l’ecografia ostetrica o l’ecografia ad alta risoluzione, in 3D o 4D, per vedere nitidamente lo stato del tuo bambino.',
		url:'data/a24.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla nona settimana di gravidanza il tuo piccolo assomiglia di più a un bambino: la sua testa è grossa e ripiegata in avanti verso il torace, la coda è sparita e la schiena si è raddrizzata.',
		url:'data/a25.html',
		hasChild:true,
		header:'Settimana 9',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei arrivata alla nona settimana di gravidanza e anche se ancora non si vede che sei incinta, potresti sentire la cintura stringere in vita.',
		url:'data/a26.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'I tuoi capelli',
		intro:'I capelli, durante la gravidanza, crescono più folti e più belli, a differenza dei peli superflui che, fortunatamente, diminuiscono. A volte però cambiano in peggio: più grassi o più aridi.',
		url:'data/a27.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'La decima settimana di gravidanza è quella in cui l’embrione che è cresciuto in te finora si trasforma in feto. Un cambiamento dovuto al fatto che ora il suo corpo è quasi completo.',
		url:'data/a28.html',
		hasChild:true,
		header:'Settimana 10',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla 10ª settimana di gravidanza ed il tuo umore è sempre più instabile? Non ti preoccupare, rientra nella normalità.',
		url:'data/a29.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Vertigini e svenimenti',
		intro:'Provare un po’ di stordimento o sensazione di vertigine è abbastanza comune in gravidanza. Durante i primi mesi, le vertigini o gli svenimenti, possono essere disturbi dovuti all’adattamento del sistema circolatorio e all’aumento del flusso sanguigno.',
		url:'data/a30.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Sei alla 11ª settimana di gravidanza. Il tuo bambino ha ormai passato la fase critica dello sviluppo e d’ora in poi il rischio di sviluppare anomalie congenite o di contrarre infezioni si abbassa notevolmente.',
		url:'data/a31.html',
		hasChild:true,
		header:'Settimana 11',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei arrivata all’11ª settimana di gravidanza e pesandoti hai scoperto di aver preso un chilo. Tranquilla, nei primi tempi della gravidanza è normale aumentare di peso.',
		url:'data/a32.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Tubercoli di Montgomery',
		intro:'I tubercoli di Montgomery sono delle ghiandolette poste sulle areole, ovvero dei piccoli rilievi dovuti all’aumento di volume delle ghiandole sebacee del seno.',
		url:'data/a33.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'È incredibile quello che il bambino è già in grado di fare durante la 12ª settimana di gravidanza: muove braccia, gambe e dita; sorride e aggrotta la fronte; succhia il pollice.',
		url:'data/a34.html',
		hasChild:true,
		header:'Settimana 12',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla 12ª settimana di gravidanza e quindi hai fatto l’ecografia e lo hai visto! È stato bellissimo, è vero?',
		url:'data/a35.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Test di translucenza nucale',
		intro:'Se hai più di 35 anni di età e aspetti un bambino, è possibile che allo stadio in cui ti trovi, alla 12ª settimana di gravidanza, ti venga suggerito di fare un test di translucenza nucale.',
		url:'data/a36.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 13ª settimana di gravidanza il tuo bambino ha cominciato a sviluppare il senso dell’udito. Le orecchie non saranno completamente formate fino alla 24ª settimana, ma il bambino potrebbe già “sentire” i suoni attraverso recettori di vibrazioni localizzati nell’epidermide.',
		url:'data/a37.html',
		hasChild:true,
		header:'Settimana 13',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Arrivata alla 13ª settimana di gravidanza, stai bene e il rischio di aborto si è ridotto del 65% circa.',
		url:'data/a38.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'L’udito del feto',
		intro:'Il modo in cui il feto reagisce ai suoni è stato ampiamente indagato, sostanzialmente perché l’udito è il senso più facile da stimolare all’interno dell’utero.',
		url:'data/a39.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'La 14ª settimana segna l’inizio del secondo trimestre della tua gravidanza.',
		url:'data/a40.html',
		hasChild:true,
		header:'Settimana 14',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla 14ª settimana di gravidanza, l’inizio del secondo trimestre. Nel secondo trimestre, molti dei disturbi iniziali della gravidanza, come le nausee mattutine, scompariranno e comincerai a recuperare le forze e a sentirti come prima di rimanere incinta.',
		url:'data/a41.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Curiosità',
		intro:'Ti sei mai chiesta come fa il tuo bambino a galleggiare nel liquido amniotico senza affogare?',
		url:'data/a42.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Lo sapevi che alla 15ª settimana di gravidanza il tuo bambino può già aggrottare la fronte e fare le smorfie?',
		url:'data/a43.html',
		hasChild:true,
		header:'Settimana 15',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei incinta da 15 settimane: hai ormai certamente difficoltà nel chiudere gonne e pantaloni, ed è quindi giunta l’ora di riformare il guardaroba di indumenti adatti.',
		url:'data/a44.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'5 accessori utili',
		intro:'Ci sono cinque accessori che ti potrebbero servire in gravidanza. Mettili nel tuo guardaroba premaman.',
		url:'data/a45.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 16ª settimana il tuo bambino pesa circa 80 grammi e gli arti del tuo bambino sono interamente formati.',
		url:'data/a46.html',
		hasChild:true,
		header:'Settimana 16',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla 16ª settimana di gravidanza: per te, è tempo di controlli e di conoscere i risultati degli esami del sangue. Forse potrai sentire il battito del tuo bambino durante l’ecografia.',
		url:'data/a47.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Igiene orale',
		intro:'L’igiene orale è importantissima in gravidanza.  Gli ormoni della gravidanza infatti, rendono la bocca molto più delicata e soggetta a problemi.',
		url:'data/a48.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Arrivata alla 17ª settimana di gravidanza il tuo bambino pesa già 100 grammi e la sua testa, seppure ancora grossa, comincia a proporzionarsi.',
		url:'data/a49.html',
		hasChild:true,
		header:'Settimana 17',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Alla 17ª settimana di gravidanza continuerai a notare i cambiamenti che il tuo corpo sta subendo.',
		url:'data/a50.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Stimolando il bambino',
		intro:'Il tuo bambino mentre sta nel tuo grembo è in grado di ricevere e rispondere agli stimoli che vengono dall’esterno.',
		url:'data/a51.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'In questa fase, durante la 18ª settimana di gravidanza, il tuo  bambino non conosce tregua.',
		url:'data/a52.html',
		hasChild:true,
		header:'Settimana 18',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla 18ª settimana della tua gravidanza: a questo stadio avrai probabilmente recuperato le energie e ritrovato il desiderio sessuale.',
		url:'data/a53.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Sesso in gravidanza',
		intro:'Fare l’amore fa bene. Dopo i divieti, finalmente un incoraggiamento.',
		url:'data/a54.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 19ª settimana diventano visibili i capezzoli e gli organi genitali interni sono tutti al loro posto. Se il tuo bambino è  maschio i genitali esterni son ben riconoscibili.',
		url:'data/a55.html',
		hasChild:true,
		header:'Settimana 19',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla 19ª settimana di gravidanza. Sei elettrizzata! L’hai sentito muoversi! Sono passate solo tre settimane da quando scalciava ma non potevi sentirlo.',
		url:'data/a56.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Incinta: mangio di più?',
		intro:'Di quante calorie in più pensi di avere bisogno adesso che sei incinta? Ben 200, per un totale di 2150-2300 calorie.',
		url:'data/a57.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 20ª settimana di gravidanza il feto è giunto a metà del cammino. È ancora piccolo, ma cresce rapidamente.',
		url:'data/a58.html',
		hasChild:true,
		header:'Settimana 20',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Questa settimana solitamente coincide con la terza visita prenatale. È tempo infatti di fare l’ecografia morfologica per vedere come va lo sviluppo del tuo bambino.',
		url:'data/a59.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Pancia sì, pancia no',
		intro:'Ti stai chiedendo quando inizierà a vedersi la pancia? Hai voglia di guardarti allo specchio e vedere già il pancione?',
		url:'data/a60.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Sei alla 21ª settimana di gravidanza e il tuo bambino pesa circa 300 grammi. Il piccolo continua ad acquistare peso, cosa essenziale per mantenere la temperatura corporea dopo la nascita.',
		url:'data/a61.html',
		hasChild:true,
		header:'Settimana 21',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'A gravidanza inoltrata è normale che una serie di cambiamenti avvengano nel tuo corpo e che alcuni di questi siano “spiacevoli”.',
		url:'data/a62.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Linea nigra',
		intro:'Hai anche tu una linea scura sul pancione? È la linea nigra.',
		url:'data/a63.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Hai sentito parlare dei ritmi sonno-veglia del feto? La 22ª settimana è proprio quella in cui si registreranno fasi alterne di veglia e sonno nel tuo bambino.',
		url:'data/a64.html',
		hasChild:true,
		header:'Settimana 22',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Hai notato un aumento dell’appetito durante questa 22ª settimana? Se è così, cerca di evitare cibi non sani e snack industriali, anche se a volte ti viene una voglia irrefrenabile di mangiare qualche “schifezza”.',
		url:'data/a65.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Ritmi sonno-veglia',
		intro:'Ancora prima di nascere, il tuo bambino avrà, proprio come un neonato, dei ritmi regolari di sonno e di veglia.',
		url:'data/a66.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 23ª settimana di gravidanza, le proporzioni fra testa e corpo si stanno normalizzando ogni giorno di più e ormai l’aspetto è quello di un bambino pronto per il parto, nonostante ossa e organi siano ancora visibili attraverso la pelle.',
		url:'data/a67.html',
		hasChild:true,
		header:'Settimana 23',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'La tua pancia è sempre più grossa, è vero?',
		url:'data/a68.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Curiosità',
		intro:'Lo sapevi che di tutti i suoni e rumori che il tuo bambino può percepire, la tua voce, la voce materna è la più frequente?',
		url:'data/a69.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 24ª settimana di gravidanza la testa del tuo bambino sarà ancora sproporzionata rispetto al corpo esile che si sta allungando. I tratti del viso invece sono già ben definiti. Ha persino ciglia e sopracciglia ben delineate.',
		url:'data/a70.html',
		hasChild:true,
		header:'Settimana 24',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Durante la 24ª settimana della tua gravidanza ti potrà capitare di avvertire qualche contrazione, che prepara il tuo corpo al parto.',
		url:'data/a71.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Esercizi di Kegel',
		intro:'La ginnastica di Kegel, concepita dal dottor Arnold Kegel, permette di tonificare i muscoli del perineo, o del pavimento pelvico, con degli esercizi specifici, in modo che possano sostenere correttamente il peso del pancione e contribuire adeguatamente alla spinta durante il parto.',
		url:'data/a72.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Lo sai che alla 25ª settimana di gravidanza il tuo bambino è in grado di prendersi i piedi e stringere la mano a pugno?',
		url:'data/a73.html',
		hasChild:true,
		header:'Settimana 25',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sono ormai 25 settimane che sei incinta: sei a più che metà cammino!',
		url:'data/a74.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Corsi preparto',
		intro:'La nascita è un momento così naturale della vita che potrebbe sembrare insolito doversi organizzare. Tuttava, i corsi pre-parto hanno un ruolo fondamentale.',
		url:'data/a75.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 26ª settimana il feto possiede unghie, ciglia e sopracciglia e gli occhi sono completamente formati.',
		url:'data/a76.html',
		hasChild:true,
		header:'Settimana 26',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Questa è la 26ª settimana di gravidanza, non ti sorprenderà di certo notare come la tua pancia continua a crescere...',
		url:'data/a77.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Curiosità',
		intro:'Lo sapevi perché il bambino nel pancione si succhia il pollice?',
		url:'data/a78.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 27ª settimana di gravidanza il tuo bambino è più paffuto, comincia a irrobustirsi: al di sotto dell’epidermide si sta accumulando il grasso.',
		url:'data/a79.html',
		hasChild:true,
		header:'Settimana 27',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei alla fine del secondo trimestre: il tuo addome sarà sicuramente piuttosto prominente...',
		url:'data/a80.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Gusto e olfatto del feto',
		intro:'Il bambino già nel pancione sperimenta il senso del gusto e dell’olfatto, perché il liquido amniotico contiene i sapori e gli odori dei cibi consumati da te.',
		url:'data/a81.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Sapevi che alla 28ª settimana di gravidanza, il bambino si irrobustisce e ingrassa e il tono muscolare migliora?  Raggiunge un terzo del peso previsto dalla nascita e accumula grasso sottocutaneo.',
		url:'data/a82.html',
		hasChild:true,
		header:'Settimana 28',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Con la 28ª settimana, l’inizio del terzo trimestre della tua gravidanza, noterai che sei sempre più grossa e soffrirai di qualche disturbo.',
		url:'data/a83.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'L’udito del feto',
		intro:'Lo sapevi che l’udito è il senso più facile da stimolare all’interno dell’utero? Il tuo bambinoha già cominciato a reagire ai suoni intorno alla 24ª settimana, assumendo comportamenti più decisi all’aumentare dell’intensità del suono.',
		url:'data/a84.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 29ª settimana di gravidanza, la testa è ormai proporzionata rispetto al corpo.  Il tuo bambino continua a ingrassare e cervello e organi interni a perfezionarsi.',
		url:'data/a85.html',
		hasChild:true,
		header:'Settimana 29',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'In alcuni casi intorno alla 29ª settimana, la pressione delle vene che portano il sangue dalle gambe al cuore potrebbe causare l’insorgenza di varici.',
		url:'data/a86.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'La vista del feto',
		intro:'La vista è il senso meno stimolato nel mondo acquatico in cui vive il tuo bambino, ed è anche l’ultimo a svilupparsi in ordine di tempo.',
		url:'data/a87.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'In questa 30ª settimana di gravidanza il tuo bambino misura circa 27 centimetri e pesa all’incirca 1, 37 chilogrammi. Ora è molto più paffuto.',
		url:'data/a88.html',
		hasChild:true,
		header:'Settimana 30',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Cara futura mamma ormai mancano solo dieci settimane per il gran momento. Sei già arrivata alla 30ª settimana di gravidanza.',
		url:'data/a89.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Birth plan',
		intro:'Alla 30ª settimana di gravidanza, se non lo hai fatto prima, potresti iniziare a valutare il Birth Plan. In italiano anche conosciuto come Piano del Parto: è un  accordo scritto e firmato tra te, partoriente, e la struttura in cui hai deciso di partorire, o con il ginecologo o l’ostetrica che ti segue.',
		url:'data/a90.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Mancano nove settimane per il suo arrivo. Questa è la 31ª settimana di gravidanza: il tuo bambino è lungo circa 28 centimetri e pesa all’incirca 1,59 chilogrammi.',
		url:'data/a91.html',
		hasChild:true,
		header:'Settimana 31',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Già da un po’ ti senti lenta e goffa nei movimenti. Non ti preoccupare. Cara futura mamma, sei alla 31ª settimana di gravidanza ed è normale che tu sia totalmente scoordinata.',
		url:'data/a92.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'I movimenti fetali',
		intro:'Nel tuo grembo, il bambino è come un piccolo acrobata e impara a compiere una serie di movimenti essenziali per la vita del mondo esterno.',
		url:'data/a93.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Lo sapevi che alla 32ª settimana di gravidanza il tuo bambino ha acquisito un’altra abilità? Adesso gira la testa da un lato all’altro. Dovrebbe anche essersi già ruotato a testa in giù.',
		url:'data/a94.html',
		hasChild:true,
		header:'Settimana 32',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sei già arrivata alla 32ª settimana di gravidanza: il tuo utero sta raggiungendo la massima altezza, con la parte superiore circa 12 centimetri dall’ombelico. Il margine superiore sovrasta di circa 12 centimetri  il tuo ombelico.',
		url:'data/a95.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Posizioni del feto',
		intro:'Il feto, fino alla 32ª settimana di gravidanza, è ancora relativamente piccolo e ha spazio per muoversi nell’utero, successivamente diventa più grande e solitamente si sistema nella posizione più comoda.',
		url:'data/a96.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Hai già iniziato il conto alla rovescia? Il grande momento è ogni volta più vicino. Sei già alla 33ª settimana di gravidanza.',
		url:'data/a97.html',
		hasChild:true,
		header:'Settimana 33',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Questa è la 33ª settimana di gravidanza e all’improvviso respiri di nuovo senza difficoltà perché il bambino si è girato definitivamente a testa in giù.',
		url:'data/a98.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Corredino',
		intro:'Prima di iniziare gli acquisti per il corredino del tuo bambino faresti bene a leggere qualche consiglio per evitare di comprare troppe cose o le cose sbagliate.',
		url:'data/a99.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Questa è la 34ª settimana di gravidanza. Il bambino è lungo 32 centimetri e pesa ormai più di due chili, per l’esattezza dovrebbe pesare 2,3 chilogrammi.',
		url:'data/a100.html',
		hasChild:true,
		header:'Settimana 34',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Cara futura mamma alla 34ª settimana di gravidanza ti renderai subito conto di come ingrosserai più velocemente.',
		url:'data/a101.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Abbigliamento premaman',
		intro:'Quando scegli un capo premaman, chiediti sempre quando pensi di indossarlo.',
		url:'data/a102.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'A questo stadio il grasso continua ad accumularsi e il tuo bambino è sempre più paffuto. Il 99% dei bambini che nascono nella 35ª settimana non ha grossi problemi a sopravvivere.',
		url:'data/a103.html',
		hasChild:true,
		header:'Settimana 35',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Sono passate in fretta queste 35 settimane? Quasi senza accorgertene sei arrivata alla 35ª settimana della tua gravidanza.',
		url:'data/a104.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Contrazioni: vere o “false”',
		intro:'Le contrazioni sono l’unico segnale certo che sei in travaglio. Già negli ultimi mesi di gravidanza inizierai a sentire delle contrazioni uterine irregolari, non dolorose e distanziate nel tempo.',
		url:'data/a105.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 36ª settimana di gravidanza, il tuo bambino ha ormai quasi raggiunto la lunghezza definitiva e il suo peso continua ad aumentare.',
		url:'data/a106.html',
		hasChild:true,
		header:'Settimana 36',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Cara futura mamma, giunta alla 36ª settimana di gravidanza, le visite prenatali avverranno con cadenza settimanale, fino al parto.',
		url:'data/a107.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'La borsa per l’ospedale',
		intro:'Poiché è del tutto normale che il parto si verifichi con una o due settimane di anticipo, almeno quattro settimane prima dello scadere del termine, quindici o venti giorni prima della data prevista, dovrai preparare la valigia da portare in ospedale.',
		url:'data/a108.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Alla 37ª settimana di gravidanza, la tua gestazione è ormai considerata a termine, d’ora in poi il tuo bambino può nascere da un momento all’altro.',
		url:'data/a109.html',
		hasChild:true,
		header:'Settimana 37',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Cara futura mamma, ci siamo quasi. Ormai alla 37ª settimana di gravidanza, le misure e il peso del bambino saranno controllati a ogni monitoraggio.',
		url:'data/a110.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Contrazioni di Braxton Hicks',
		intro:'Ti potrebbe capitare durante queste settimane di avere delle contrazioni che però non sono vere contrazioni. Sono conosciute come le contrazioni di Braxton Hicks, dal nome del medico che per primo le identificò.',
		url:'data/a111.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Mancano solo due settimane! Questa è la 38ª settimana di gravidanza. Il tuo bambino pesa 3,1 chilogrammi ed è lungo 36 centimetri. È clinicamente pronto al parto in qualsiasi momento.',
		url:'data/a112.html',
		hasChild:true,
		header:'Settimana 38',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Ormai mancano solo due settimane per il grande momento. Questa è la 38ª settimana di gravidanza e sai di essere irritabile perché sei stanca e preoccupata per il parto.',
		url:'data/a113.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Massaggi in gravidanza',
		intro:'Più volte ti sarai sorpresa ad accarezzare il tuo pancione per stabilire un contatto con il bambino e infondergli sicurezza? Con il massaggio si possono ricavare anche altri benefici.',
		url:'data/a114.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'La tue settimane di gravidanza stanno arrivando al termine e il tuo piccolo sta per nascere. Lo sapevi che il cordone ombelicale ha ormai raggiunto i 51 centimetri di lunghezza ed è lungo quasi quanto il bambino dalla testa ai piedi?',
		url:'data/a115.html',
		hasChild:true,
		header:'Settimana 39',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'Alla 39ª settimana l’utero occupa ormai tutto lo spazio della regione pelvica e gran parte dell’addome ed è normale che provochi una sensazione di estremo disagio.',
		url:'data/a116.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'Il parto',
		intro:'Il parto è probabilmente il momento più temuto di tutta la gravidanza. Molte mamme, soprattutto se si tratta della prima gravidanza, diventano nervose solo pensando al momento in cui nascerà il loro bebè',
		url:'data/a117.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
	{
		title:'Il tuo bambino',
		intro:'Ultima settimana della tua gravidanza: la 40ª. Se il tuo bambino non è nato finora, preparati perché si tratta di giorni o forse di ore. Stai immaginando già il momento in cui terrai in braccio il fagottino? Che emozione!',
		url:'data/a118.html',
		hasChild:true,
		header:'Settimana 40',
		leftImage:'data/images/bebe.gif',
	},
	{
		title:'Il tuo corpo',
		intro:'La 40ª settimana di gravidanza è quella in cui scade la gestazione, in cui in teoria dovrebbe nascere il tuo bambino. Ma solo il 5% dei bambini nasce esattamente alla data prevista del parto. È più comune che partorisca un paio di settimane in anticipo o in ritardo.',
		url:'data/a119.html',
		hasChild:true,
		leftImage:'data/images/mama.gif',
	},
	{
		title:'DPP: anticipi e ritardi',
		intro:'Solo cinque bambini su cento nascono proprio alla data prevista: circa trenta su cento sono in anticipo e sessantacinque su cento sono in ritardo.',
		url:'data/a120.html',
		hasChild:true,
		leftImage:'data/images/general.gif',
	},
];